apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-project
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: httpd
          imagePullPolicy: Always
